- name: Create resources
  block:
    - name: Start role creation
      k8s:
        state : present
        definition: "{{ lookup('file', 'rbac-config-template.yml')}}"

    - name: Check resource presence
      include: check.yml
  when: with_resources

- name: Create backup
  include_role:
    name: backup
  when: with_backup

- name: Restore service account
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore

    - name: Check resource presence
      include: check.yml
