---
apiVersion: ark.heptio.com/v1
kind: Backup
metadata:
  name: mysql-centos7-imagestream-backup
  namespace: heptio-ark
spec:
  labelSelector:
    matchLabels:
      app: mysql
  storageLocation: default
  ttl: 720h0m0s
  includedNamespaces:
  - '*'
