---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-centos7-imagestream
  labels:
    app: mysql
---
apiVersion: v1
kind: ImageStream
metadata:
  namespace: mysql-centos7-imagestream
  annotations:
    openshift.io/display-name: MySQL
  name: mysql
  labels:
    app: mysql
spec:
  tags:
  - annotations:
      description: Provides a MySQL database on CentOS 7. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/mysql-container/blob/master/README.md.
      iconClass: icon-mysql-database
      openshift.io/display-name: MySQL (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: mysql
    from:
      kind: ImageStreamTag
      name: '8.0'
    name: latest
    referencePolicy:
      type: Local
  - annotations:
      description: Provides a MySQL 5.5 database on CentOS 7. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/mysql-container/blob/master/README.md.
      iconClass: icon-mysql-database
      openshift.io/display-name: MySQL 5.5
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: hidden,mysql
      version: '5.5'
    from:
      kind: DockerImage
      name: docker.io/openshift/mysql-55-centos7:latest
    name: '5.5'
    referencePolicy:
      type: Local
