---
- name: Create route
  block:
    - name: Create the namespace, service and route
      k8s:
        state: present
        definition: "{{ lookup('file', 'base.yml')}}"
      register: deploy
      retries: 10
      delay: 3
      until: deploy is succeeded

    - name: Check resource presence
      include: check.yml
  when: with_resources

- name: Create backup
  include_role:
    name: backup
  when: with_backup

- name: Restore route
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore

    - name: Check resource presence
      include: check.yml
