---
- name: Create route
  block:
    - name: Create the namespace, service and route
      k8s:
        state: present
        definition: "{{ lookup('file', 'base.yml')}}"

    - name: Checking the route before backup
      k8s_facts:
        api_version: route.openshift.io/v1
        kind: Route
        namespace: route-example
        name: route-one
      register: route
      until: route.resources | length > 0
      retries: 10
      delay: 3

- name: Create route and backup
  block:
    - name: Create backup
      include_role:
        name: backup
      vars:
        backup_name: route-backup
        backup_label: route

# Restore part
- name: Restore route
  when: not travisCI
  block:
    - name: Start restoring 
      include_role:
        name: restore
      vars:
        restore_name: route-restore
        backup_name: route-backup
        namespace_to_delete: route-example

    - name: Checking the route after restore
      k8s_facts:
        api_version: route.openshift.io/v1
        kind: Route
        namespace: route-example
        name: route-one
      register: route
      until: route.resources | length > 0
      retries: 10
      delay: 3
