---
apiVersion: ark.heptio.com/v1
kind: Backup
metadata:
  name: nginx-deployment-backup
  namespace: heptio-ark
spec:
  labelSelector:
    matchLabels:
      app: nginx-deployment
  storageLocation: default
  ttl: 720h0m0s
  includedNamespaces:
  - '*'
