---
apiVersion: ark.heptio.com/v1
kind: Backup
metadata:
  name: service-basic-backup
  namespace: heptio-ark
spec:
  labelSelector:
    matchLabels:
      name: my-service
  storageLocation: default
  ttl: 720h0m0s
  includedNamespaces:
  - '*'
