---
apiVersion: v1
kind: Namespace
metadata:
  name: service-example
  labels:
    name: my-service

---
kind: Service
apiVersion: v1
metadata:
  name: my-service
  namespace: service-example
  labels:
    name: my-service
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9376
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9377                       