---
- name: debug info
  debug:
   msg: "Logging into cluster using KUBECONFIG: {{ ansible_env.KUBECONFIG }}"

- name: login to cluster
  vars:
    kubeadmin_password: "{{ ansible_env.kubeadmin_password }}"
  shell: oc login -u admin -p {{ kubeadmin_password }}
