- name: Deploy nginx-deployment
  block:
    - name: Deploy nginx-deployment pod using deployment resource
      k8s:
        state: present
        definition: "{{ lookup('file', 'nginx-deployment-template.yml')}}"

    - name: Check for deployment presence
      k8s_facts:
        kind: Deployment
        api_version: apps/v1
        namespace: nginx-deployment
        label_selectors: "app=nginx-deployment"
      register: deploy
      until:  deploy.get("resources", [])
              and deploy.resources[0].get("status", {}).get("replicas", -1) == deploy.resources[0].get("status", {}).get("availableReplicas", 0)
      retries: 10
      delay: 10

- name: Create backup
  block:
    - name: Create backup
      include_role:
        name: backup
      vars:
        backup_name: nginx-deployment-backup
        backup_label: nginx-deployment

- name: Restore service
  when: not travisCI
  block:
    - name: Start restoring 
      include_role:
        name: restore
      vars:
        restore_name: nginx-deployment-restore
        backup_name: nginx-deployment-backup
        namespace_to_delete: nginx-deployment

    - name: Check for deployment presence
      k8s_facts:
        kind: Deployment
        api_version: apps/v1beta1
        namespace: nginx-deployment
        label_selectors: "app=nginx-deployment"
      register: deploy
      until:  deploy.get("resources", [])
              and deploy.resources[0].get("spec", {}).get("replicas", -1) == deploy.resources[0].get("status", {}).get("availableReplicas", 0)
      retries: 10
      delay: 10
