# Deploy pod
- name: Deploy hello pod using deployment resource
  k8s:
    state: present
    definition: "{{ lookup('file', 'nginx-deployment-template.yml')}}"

- name: Check for deployment presence
  debug:
    var: deploy
  until: deploy and deploy.status.replicas == deploy.status.get("availableReplicas", 0)
  retries: 10
  delay: 10
  vars:
    deploy: '{{ lookup("k8s",
      kind="Deployment",
      api_version="apps/v1",
      namespace="nginx-deployment",
      label_selector="app=nginx-deployment"
    )}}'

# Create a backup
- name: Create ark backup of hello pod
  k8s:
    state : present
    definition: "{{ lookup('file', 'create-backup-nginx-deployment.yml')}}"

- name: Wait for backup to complete
  debug:
    var: backup
  until: backup and backup.status.get("phase", 0) == "Completed"
  retries: 10
  delay: 5
  vars:
    backup: '{{ lookup("k8s",
      kind="Backup",
      api_version="ark.heptio.com/v1",
      namespace="heptio-ark",
      resource_name="nginx-deployment-backup"
    )}}'

# Simulate DR and restore
- name: Delete hello pod
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: nginx-deployment

- name: Wait 2 minutes for namespace to be deleted
  debug:
    var: ns
  until:  not ns
  retries: 10
  delay: 5
  vars:
    ns: '{{ lookup("k8s",
      kind="Namespace",
      api_version="v1",
      resource_name="nginx-deployment"
    )}}'

- name: Create ark restore of hello pod
  k8s:
    state: present
    definition: "{{ lookup('file', 'create-restore-nginx-deployment.yml')}}"

- name: Wait for restore to finish
  debug:
    var: restore
  until: restore and restore.status.get("phase", 0) == "Completed"
  retries: 20
  delay: 10
  vars:
    restore: '{{ lookup("k8s",
      kind="Restore",
      api_version="ark.heptio.com/v1",
      namespace="heptio-ark",
      resource_name="nginx-deployment-restore"
    )}}'

- name: Check for deployment presence
  debug:
    var: deploy
  until: deploy and deploy.status.replicas == deploy.status.get("availableReplicas", 0)
  retries: 10
  delay: 10
  vars:
    deploy: '{{ lookup("k8s",
      kind="Deployment",
      api_version="apps/v1",
      namespace="nginx-deployment",
      label_selector="app=nginx-deployment"
    )}}'

- name: Delete ark restore of hello pod (workaround to use common name for restore)
  k8s:
    state: absent
    definition: "{{ lookup('file', 'create-restore-nginx-deployment.yml')}}"
