apiVersion: v1
kind: Namespace
metadata:
  name: "custom-build-ns"
  labels:
    app: custom-build

---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "ruby-sample-build" # ruby-sample-build
  namespace: "custom-build-ns"
  labels:
    app: custom-build
spec:
  runPolicy: "Serial" 
  triggers: 
    -
      type: "GitHub"
      github:
        secret: "secret101"
    - type: "Generic"
      generic:
        secret: "secret101"
        allowEnv: true
    -
      type: "ImageChange"
  source: 
    git:
      uri: "https://github.com/openshift/ruby-hello-world"
  strategy:
    customStrategy:
      from:
        kind: "DockerImage"
        name: "docker.io/centos:7"
  postCommit: 
      script: "bundle exec rake test"

