- name: Create etcd
  block:
    - name: Create HA etcd
      k8s:
        state: present
        definition: "{{ lookup('file', 'ha-etcd-template.yml')}}"

    - name: Check resource presence
      include: check.yml

- name: Create backup
  when: with_backup
  block:
    - name: Create backup
      include_role:
        name: backup

- name: Restore resource
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore

    - name: Check resource presence
      include: check.yml
