# https://github.com/fusor/ocp-velero-ansible/tree/master/roles
---
- name: Create resources
  block:
    - name: Create Nginx application
      k8s:
        state: "{{ state }}"
        definition: "{{ lookup('file', 'base.yml')}}"

    - name: Check resource presence
      include: check.yml
  when: with_resources 

- name: Create backup
  include_role:
    name: backup
  when: with_backup

- name: Restore resources
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore

    - name: Check resource presence
      include: check.yml
