---
apiVersion: ark.heptio.com/v1
kind: Backup
metadata:
  name: sa-role-backup
  namespace: heptio-ark
spec:
  labelSelector:
    matchLabels:
      app: basic-sa-role
  storageLocation: default
  ttl: 720h0m0s
  includedNamespaces:
  - '*'
