---
- name: Create Pipeline
  block:
    - name: Create Jenkins-pipeline BuildConfig
      k8s:
        state: present
        definition: "{{ lookup('file', 'install-pipeline-example.yml')}}"
      register: deploy
      retries: 10
      delay: 3
      until: deploy is succeeded

    - name: Check resource presence
      include: check.yml
  when: with_resources
  
- name: Create backup
  include_role:
    name: backup
  when: with_backup

- name: Restore pipeline
  when: with_restore
  block:
    - name: Start restoring
      include_role:
        name: restore

    - name: Check resource presence
      include: check.yml
