- name: Wait for kafka to run
  k8s_facts:
    kind: StatefulSet
    namespace: ha-kafka
    name: kafka
  register: stateful_set
  until: stateful_set.get("resources", []) and stateful_set.resources[0].get("status", {}).get("readyReplicas", "") == 3
  retries: 20
  delay: 10

- name: Wait for client pod to run
  k8s_facts:
    kind: Pod
    namespace: ha-kafka
    name: kafka-test-client
  register: pod
  until: pod.get("resources", []) and pod.resources[0].get("status", {}).get("phase", "") == "Running"
  retries: 20
  delay: 10
