---
kind: Namespace
apiVersion: v1
metadata:
  name: cron-job-ns
  labels:
    app: cron
    
---
# src https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#creating-a-cron-job
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: cron-job-ns
  name: hello
  labels:
    app: cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: Never
