---
apiVersion: ark.heptio.com/v1
kind: Backup
metadata:
  name: cakephp-backup
  namespace: heptio-ark
spec:
  labelSelector:
    matchLabels:
      app: cakephp-example
  storageLocation: default
  ttl: 720h0m0s
  includedNamespaces:
  - '*'
