- name: Check job exists and running
  k8s_facts:
    api_version: batch/v1
    kind: Job
    namespace: job-ns
    name: hello
  register: job
  retries: 20
  delay: 5
  until:  job.get("resources", []) and
          job.resources[0].get("status").get("active", 0) == 0 and
          job.resources[0].status.get("succeeded", 0) == 1
