- name: Deploy job
  k8s:
    state: present
    definition: "{{ lookup('file', 'job-template.yml') }}"

- name: Check resource presence
  include: check.yml

- name: Create backup
  include_role:
    name: backup
  when: with_backup

- name: Restore job
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore

    - name: Check resource presence
      include: check.yml
