---
- name: Create service
  block:
    - name: Create service example
      k8s:
        state: present
        definition: "{{ lookup('file', 'service-template.yml') }}"
      register: deploy
      retries: 10
      delay: 3
      until: deploy is succeeded

    - name: Check resource presence
      include: check.yml
  when: with_resources
  
- name: Create a backup
  when: with_backup
  block:
    - name: Create backup
      include_role:
        name: backup

- name: Restore service
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore

    - name: Check resource presence
      include: check.yml
