---
apiVersion:
kind: Namespace
metadata: 
  name: rep-sets-ns
  labels:
    app: rep-set

# Source: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep-set
  namespace: rep-sets-ns
  labels:
    app: rep-set
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift
