- name: Create resources
  block:
    - name: Create CRD
      k8s:
        state: present
        definition: "{{ lookup('file', 'crd-template.yml')}}"
      register: deploy
      retries: 10
      delay: 3
      until: deploy is succeeded

    - name: Check resource presence
      include: check.yml

    - name: Create custom resource
      k8s:
        state: present
        definition:
          apiVersion: samplecontroller.k8s.io/v1alpha1
          kind: CRExample
          metadata:
            name: cr-example
            namespace: crd-example
            labels:
              name: crd-example
          spec:
            deploymentName: cr-example
            replicas: 1
  when: with_resources
  
- name: Create backup
  include_role:
    name: backup
  when: with_backup

- name: Restore service
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore

    - name: Check resource presence
      include: check.yml

    - name: Wait 2 minutes for custom resource to appear
      k8s_facts:
        api_version: samplecontroller.k8s.io/v1alpha1
        kind: CRExample
        namespace: crd-example
        name: cr-example
      register: cr_example
      until: cr_example and (cr_example.resources | length > 0)
      retries: 10
      delay: 10
