- name: Create resources
  block:
    - name: Create quotas
      k8s:
        state: present
        definition: "{{ lookup('file', 'quota_template.yml') }}"

    - name: Test resources
      include: check.yml
  when: with_resources

- name: Create backup
  include_role:
    name: backup
  when: with_backup

- name: Restore service
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore

    - name: Test resources
      include: check.yml
