# Deploy pod
- name: Deploy hello pod
  k8s:
    state: present
    definition: "{{ lookup('file', 'hellopod-template.yml')}}"

- name: Wait for pod to run
  debug:
    var: pod
  until: pod and pod.status.phase == "Running"
  retries: 20
  delay: 10
  vars:
    pod: '{{ lookup("k8s",
      kind="Pod",
      namespace="hello-pod",
      label_selector="name=hello-openshift"
    )}}'

# Create a backup
- name: Create ark backup of hello pod
  k8s:
    state : present
    definition: "{{ lookup('file', 'create-backup-hellopod.yml')}}"

- name: Wait for backup to complete
  debug:
    var: backup
  until: backup and backup.status.get("phase", 0) == "Completed"
  retries: 10
  delay: 5
  vars:
    backup: '{{ lookup("k8s",
      kind="Backup",
      api_version="ark.heptio.com/v1",
      namespace="heptio-ark",
      resource_name="hellopod-backup"
    )}}'

# Simulate DR and restore
- name: Delete hello pod
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: hello-pod

- name: Wait 2 minutes for namespace to be deleted
  debug:
    var: ns
  until:  not ns
  retries: 10
  delay: 5
  vars:
    ns: '{{ lookup("k8s",
      kind="Namespace",
      api_version="v1",
      resource_name="hello-pod"
    )}}'

- name: Create ark restore of hello pod
  k8s:
    state: present
    definition: "{{ lookup('file', 'create-restore-hellopod.yml')}}"

- name: Wait for restore to finish
  debug:
    var: restore
  until: restore and restore.status.get("phase", 0) == "Completed"
  retries: 20
  delay: 10
  vars:
    restore: '{{ lookup("k8s",
      kind="Restore",
      api_version="ark.heptio.com/v1",
      namespace="heptio-ark",
      resource_name="hellopod-restore"
    )}}'

- name: Wait for pod to run
  debug:
    var: pod
  until: pod and pod.status.phase == "Running"
  retries: 20
  delay: 10
  vars:
    pod: '{{ lookup("k8s",
      kind="Pod",
      namespace="hello-pod",
      label_selector="name=hello-openshift"
    )}}'

- name: Delete ark restore of hello pod (workaround to use common name for restore)
  k8s:
    state: absent
    definition: "{{ lookup('file', 'create-restore-hellopod.yml')}}"
