- name: Deploy pod
  block:
    - name: Create pod
      k8s:
        state: present
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: hello-pod
            labels:
              name: hello-openshift
              app: hello-openshift

    - name: Create pod
      k8s:
        state: present
        definition:
          kind: Pod
          apiVersion: v1
          metadata:
            name: hello-openshift
            namespace: hello-pod
            creationTimestamp: 
            labels:
              name: hello-openshift
          spec:
            containers:
            - name: hello-openshift
              image: openshift/hello-openshift

    - name: Wait for pod to run
      k8s_facts:
        kind: Pod
        namespace: hello-pod
        label_selectors: "name=hello-openshift"
      register: pod
      until:  pod.get("resources", [])
              and pod.resources[0].get("status", {}).get("phase", "")
              == "Running"
      retries: 20
      delay: 10

- name: Create a backup
  when: with_backup
  block:
    - name: Create backup
      include_role:
        name: backup
      vars:
        backup_name: hellopod-backup
        backup_label: hello-openshift

- name: Restore pod
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore
      vars:
        restore_name: hellopod-restore
        backup_name: hellopod-backup
        namespaces_to_delete:
          - hello-pod

    - name: Wait for pod to run
      k8s_facts:
        kind: Pod
        namespace: hello-pod
        label_selectors: "name=hello-openshift"
      register: pod
      until: pod.get("resources", []) and pod.resources[0].get("status", {}).get("phase", "") == "Running"
      retries: 20
      delay: 10
